---
title: "De mooiste RMarkdown"
author: "Teun van Dorp, Luc Hengeveld, Michelle Memelink"
date: "11/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## De mooie code

```{r aanmaken}
library(edgeR)
fDir <-  "/home/teun/Documents/HAN/Jaar 2/Blok 6/R markdown/"
fName <- "WCFS1_cnts.txt"

cnts <- read.delim(paste0(fDir,fName), comment.char="#")

row.names(cnts) <- cnts[,"ID"]

exp <- c("WCFS1.glc","WCFS1.glc","WCFS1.rib","WCFS1.rib")
```

```{r verwerken}
group <- factor(exp)
y <- DGEList(counts=cnts[,2:5],group=group)

print("Count statistics")
print(summary(y$counts))
print(y$samples)

design <- model.matrix(~0+group, data=y$samples)
colnames(design) <- levels(y$samples$group)
print(design)

y <- estimateGLMCommonDisp(y,design)
y <- estimateGLMTrendedDisp(y,design, method="power")
y <- estimateGLMTagwiseDisp(y,design)
```
## De plotjes
```{r plot}
plotMDS(y)
plotBCV(y)
```

```{r verder}
fit <- glmFit(y,design)

mc <- makeContrasts(exp.r=WCFS1.glc-WCFS1.rib, levels=design)

fit <- glmLRT(fit, contrast=mc)

res<-topTags(fit)
print(res)
```

```{r writeFile}
library(xlsx)
write.xlsx(fit, "foldChanges.xlsx", sheetName = "All Data", col.names = T,
           row.names = T, append = F)
write.xlsx(res, "foldChanges.xlsx", sheetName = "Higest Values", col.names = T,
           row.names = T, append = T)
```
